language: node_js
node_js:
  - "10"
cache: npm

# cache:
#   directories:
#     - node_modules

notifications:
  email:
    recipients:
      - gentleman_0109@outlook.com # 设置通知邮件
    on_success: change
    on_failure: always

# S: Build Lifecycle
install:
  - npm install hexo-cli -g
  - npm install

# before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "yubuntu0109"
  - git config user.email "Gentleman_0109@outlook.com"
  - git add .
  - git commit -m ":rocket:update my daily plans"
  - git push --force --quiet "https://${000DAYS_TOKEN}@${GH_REF}" master:master

# E: Build LifeCycle
branches:
  only:
    - Hexobackup
env:
 global:
   - GH_REF: github.com/YUbuntu0109/000days.git
